image: java:8

stages:
  - build
  - test

before_script:
  - chmod +x mvnw

build-project:
  stage: build
  script:
    - echo "Execução do build do projeto"
    - ./mvnw package

test-project:
  stage: test
  dependencies:
    - build-project
  script:
    - echo "Execução dos testes unitários"