image: java:8

stages:
  - test
  - build

before_script:
  - chmod +x mvnw

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
sonarcloud-check:
  stage: test
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  only:
    - merge_requests
    - master
    - develop

build-project:
  stage: build
  dependencies:
    - sonarcloud-check
  script:
    - echo "Execução do build do projeto"
    - ./mvnw clean package