language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "wesleyosantos91-github"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn cobertura:cobertura
before_install:
  - chmod +x mvnw

after_success:
  - curl  https://sonarcloud.io/api/qualitygates/project_status?projectKey=io.github.wesleyosantos%3Aapi-first > response

  if [ "$QGSTATUS" = "OK" ]
    then
      exit 0
  elif [ "$QGSTATUS" = "ERROR" ]
    then
      exit 1
  fi