spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password: sa
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
    flyway:
      url: ${spring.datasource.url}
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}
      locations: classpath:/db/migration

variavel:
  teste: springboot-test
