spring:
  datasource:
    url: ${database_url}
    username: ${database_username}
    password: ${database_password}
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true


